// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElTooltip: typeof import('element-plus/es/el-tooltip')['default']
    ElRow: typeof import('element-plus/es/el-row')['default']
    ElPopover: typeof import('element-plus/es/el-popover')['default']
    ElTabPane: typeof import('element-plus/es/el-tab-pane')['default']
    ElTabs: typeof import('element-plus/es/el-tabs')['default']
    ElDialog: typeof import('element-plus/es/el-dialog')['default']
    ElTag: typeof import('element-plus/es/el-tag')['default']
    ElDropdownItem: typeof import('element-plus/es/el-dropdown-item')['default']
    ElDropdownMenu: typeof import('element-plus/es/el-dropdown-menu')['default']
    ElDropdown: typeof import('element-plus/es/el-dropdown')['default']
    ElTree: typeof import('element-plus/es/el-tree')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElPopconfirm: typeof import('element-plus/es/el-popconfirm')['default']
    ElCollapseItem: typeof import('element-plus/es/el-collapse-item')['default']
    ElCollapse: typeof import('element-plus/es/el-collapse')['default']
    ElInfiniteScroll: typeof import('element-plus/es/el-infinite-scroll')['default']
  }
}

export {}
